In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
from sklearn import datasets
data = datasets.load_diabetes()  # Load the load_diabetes dataset

In [5]:
data['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ..., 
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [8]:
X = pd.DataFrame(data.data)
X.head()

0         1         2         3         4         5         6  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

          7         8         9  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [10]:
Y = pd.DataFrame(data.target)
Y.head()

0
0  151.0
1   75.0
2  141.0
3  206.0
4  135.0

In [11]:
lm = LinearRegression()   # Initiating a model
model = lm.fit(X,Y)       # Fitting the model on our variables

In [17]:
pred = model.predict(X)   # Predict for all the values of X
print(pred)[:10]          # Printing the first 10 values

[[ 206.11706979]
 [  68.07234761]
 [ 176.88406035]
 [ 166.91796559]
 [ 128.45984241]
 [ 106.34908972]
 [  73.89417947]
 [ 118.85378669]
 [ 158.81033076]
 [ 213.58408893]]


In [20]:
model.intercept_    # Represents B₀

array([ 152.13348416])

In [21]:
model.coef_      # Represents Bᵢ

array([[ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
        -792.18416163,  476.74583782,  101.04457032,  177.06417623,
         751.27932109,   67.62538639]])

In [26]:
lm.score(X,Y) #Finds the R-square for the model

0.51774942541329338